cache:
  key: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE"
  paths:
    - /cache/composer

stages:
  - test
  - release

test:unit:
  stage: test
  image: composer:2
  variables:
    TYPO3_PATH_WEB: "$PWD/.Build/Web"
    TYPO3_PATH_ROOT: "$PWD/.Build/Web"
  before_script:
    - composer install --ignore-platform-reqs
  script:
    - .Build/bin/phpunit -c .Build/Tests/UnitTests.xml
  allow_failure: true

test:php-code-sniffer:
  stage: test
  image: ekreative/php-cs-fixer:3
  script:
    - php-cs-fixer fix --dry-run --config=.Build/Tests/php-cs-fixer.php --diff --format junit > .Build/php-cs-fixer.xml
  artifacts:
    reports:
      junit:
        - .Build/php-cs-fixer.xml

"Publish new version to TER":
  stage: release
  image: composer:2
  variables:
    TYPO3_EXTENSION_KEY: "be_secure_pw"
  only:
    - tags
  before_script:
    - composer global require typo3/tailor
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$TYPO3_API_TOKEN" ] && [ -n "$TYPO3_EXTENSION_KEY" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/tailor ter:publish --comment "$TAG_MESSAGE" "$CI_COMMIT_TAG" "$TYPO3_EXTENSION_KEY"
      fi;
