services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SpoonerWeb\BeSecurePw\:
    resource: '../Classes/*'

  SpoonerWeb\BeSecurePw\Database\Event\AddForceResetPasswordLinkEvent:
    tags:
      - name: event.listener
        identifier: 'addForceResetPasswordLink'
